// claw-mem v6.35.0 — Health Reporter (TypeScript)
//
// Generates health assessment reports for index structures.
// MVP: Computes health score from index statistics.
//
// Licensed under the Apache License, Version 2.0

import * as crypto from "crypto";
import {
  HealthReport,
  HealthReportMetadata,
  IndexStat,
  IndexType,
  DEFAULT_OPTIMIZER_OPTIONS,
  DegradedQuery,
} from "./types.js";

/** Health score weights */
const SCORE_WEIGHTS = {
  hitRate: 0.4,
  coverage: 0.3,
  latency: 0.2,
  size: 0.1,
};

/** Latency baseline (ms) */
const LATENCY_BASELINE = 50;

/** Size baseline (bytes) */
const SIZE_BASELINE = 10 * 1024 * 1024; // 10MB

/** Expected latency for query types (ms) */
const EXPECTED_LATENCIES: Record<string, number> = {
  bm25: 10,
  entity_cooc: 5,
  ngram: 15,
  semantic: 30,
  transcript_time: 5,
  preference_key: 2,
};

/**
 * HealthReporter — generates health assessment reports.
 */
export class HealthReporter {
  private options: Required<typeof DEFAULT_OPTIMIZER_OPTIONS>;

  constructor(options?: typeof DEFAULT_OPTIMIZER_OPTIONS) {
    this.options = options ?? DEFAULT_OPTIMIZER_OPTIONS;
  }

  /**
   * Generate health report from index statistics.
   */
  generateReport(
    indexStats: IndexStat[],
    queriesAnalyzed: number
  ): HealthReport {
    const startTime = Date.now();

    // Calculate overall score
    const overallScore = this.calculateOverallScore(indexStats);

    // Identify unused indexes
    const unusedIndexes = this.findUnusedIndexes(indexStats);

    // Detect degraded queries (MVP: placeholder)
    const degradedQueries: DegradedQuery[] = [];

    // Build metadata
    const metadata: HealthReportMetadata = {
      assessmentTimeMs: Date.now() - startTime,
      queriesAnalyzed,
      indexesAnalyzed: indexStats.length,
      cacheHit: false,
    };

    return {
      overallScore,
      timestamp: Date.now(),
      indexStats,
      unusedIndexes,
      missingIndexes: [], // Generated by IndexEvolver
      degradedQueries,
      metadata,
    };
  }

  /**
   * Calculate overall health score.
   */
  calculateOverallScore(indexStats: IndexStat[]): number {
    if (indexStats.length === 0) {
      return 100; // No indexes = healthy (initial state)
    }

    const hitRateScore = this.calculateHitRateScore(indexStats);
    const coverageScore = this.calculateCoverageScore(indexStats);
    const latencyScore = this.calculateLatencyScore(indexStats);
    const sizeScore = this.calculateSizeScore(indexStats);

    const overall =
      hitRateScore * SCORE_WEIGHTS.hitRate +
      coverageScore * SCORE_WEIGHTS.coverage +
      latencyScore * SCORE_WEIGHTS.latency +
      sizeScore * SCORE_WEIGHTS.size;

    return Math.round(overall);
  }

  /**
   * Calculate index-specific score.
   */
  calculateIndexScore(stat: IndexStat): number {
    const hitRateComponent = stat.hitRate * 100;

    const expectedLatency = EXPECTED_LATENCIES[stat.type] ?? LATENCY_BASELINE;
    const latencyRatio = Math.min(stat.avgLatency / expectedLatency, 3);
    const latencyComponent = Math.max(100 - latencyRatio * 30, 0);

    const usageComponent = stat.queryCount > 0 ? 100 : 0;

    const sizeRatio = stat.size / SIZE_BASELINE;
    const sizeComponent = Math.max(100 - sizeRatio * 10, 50);

    return Math.round(
      hitRateComponent * 0.4 +
      latencyComponent * 0.3 +
      usageComponent * 0.2 +
      sizeComponent * 0.1
    );
  }

  // ── Private Methods ─────────────────────────────────────────────────────

  private calculateHitRateScore(indexStats: IndexStat[]): number {
    const activeStats = indexStats.filter((s) => s.queryCount > 0);
    if (activeStats.length === 0) return 100;

    const avgHitRate =
      activeStats.reduce((sum, s) => sum + s.hitRate, 0) / activeStats.length;

    return Math.round(avgHitRate * 100);
  }

  private calculateCoverageScore(indexStats: IndexStat[]): number {
    const total = indexStats.length;
    const used = indexStats.filter((s) => s.queryCount > 0).length;

    return Math.round((used / total) * 100);
  }

  private calculateLatencyScore(indexStats: IndexStat[]): number {
    const activeStats = indexStats.filter((s) => s.queryCount > 0);
    if (activeStats.length === 0) return 100;

    let totalScore = 0;
    for (const stat of activeStats) {
      const expected = EXPECTED_LATENCIES[stat.type] ?? LATENCY_BASELINE;
      const ratio = Math.min(stat.avgLatency / expected, 3);
      totalScore += Math.max(100 - ratio * 30, 0);
    }

    return Math.round(totalScore / activeStats.length);
  }

  private calculateSizeScore(indexStats: IndexStat[]): number {
    const totalSize = indexStats.reduce((sum, s) => sum + s.size, 0);
    const ratio = totalSize / SIZE_BASELINE;

    return Math.max(100 - Math.round(ratio * 10), 50);
  }

  private findUnusedIndexes(indexStats: IndexStat[]): string[] {
    const thresholdMs = this.options.unusedDaysThreshold * 24 * 60 * 60 * 1000;
    const now = Date.now();

    return indexStats
      .filter((stat) => {
        const ageMs = now - stat.createdAt;
        // Skip indexes created recently (< 24h)
        if (ageMs < 24 * 60 * 60 * 1000) return false;

        return now - stat.lastUsed > thresholdMs || stat.queryCount === 0;
      })
      .map((stat) => stat.name);
  }
}